name: 'Determinism Check'
inputs:
  sha1:
    description: 'sha256sum of first digest'
    required: true
  sha2:
    description: 'sha256sum of second digest'
    required: true
runs:
  using: "composite"
  steps:
    - name: Verify Deterministic Build
      shell: bash
      run: |
        echo "Comparing builds..."
        sha1=${{ inputs.sha1 }}
        sha2=${{ inputs.sha2 }}
        echo "Build:  $sha1"
        echo "Rebuild: $sha2"
        if [ "$sha1" != "$sha2" ]; then
          echo "❌ Builds are not deterministic!"
          exit 1
        fi
        echo "✅ Builds are deterministic"
