name: Build diffutils
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of diffutils"
        required: true
        default: 3.8
        type: string
jobs:
  gpg:
    name: Build GnuPG
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Init Hermit
        run: ./bin/hermit env --raw >> $GITHUB_ENV
      - name: Build
        run: make VERSION=${{ inputs.version }} -C diffutils
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: diffutils
          allowUpdates: true
          artifacts: "diffutils/diffutils-*.tar.xz"
          token: ${{ secrets.GITHUB_TOKEN }}
