name: MySQL client binaries lightweight packages
on:
  workflow_dispatch:
  push:
    branches:
      - mysql

jobs:
  mysql-client-macos11:
    strategy:
      matrix:
        binary: [mysql, mysqladmin]
        arch: [x86_64, arm64]
        version: [8.0.27, 8.0.28]
    name: Make a lightweight package for the ${{ matrix.arch }} ${{ matrix.binary }} binary v${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Package
        uses: ./.github/actions/mysql-macos
        id: build
        with:
          binary: ${{ matrix.binary }}
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
          platform: macos11

      - name: Rebuild Package
        uses: ./.github/actions/mysql-macos
        id: rebuild
        with:
          binary: ${{ matrix.binary }}
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
          platform: macos11

      - name: Verify Deterministic Build
        uses: ./.github/actions/determinism-check
        with:
          sha1: ${{ steps.build.outputs.artifact_sha }}
          sha2: ${{ steps.rebuild.outputs.artifact_sha }}

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: mysql-client
          allowUpdates: true
          artifacts: ${{ steps.build.outputs.artifact_path }}
          token: ${{ secrets.GITHUB_TOKEN }}

  mysql-client-macos14:
    strategy:
      matrix:
        binary: [mysql, mysqladmin]
        arch: [x86_64, arm64]
        version: [8.0.36]
    name: Make a lightweight package for the ${{ matrix.arch }} ${{ matrix.binary }} binary v${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Package
        uses: ./.github/actions/mysql-macos
        id: build
        with:
          binary: ${{ matrix.binary }}
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
          platform: macos14

      - name: Rebuild Package
        uses: ./.github/actions/mysql-macos
        id: rebuild
        with:
          binary: ${{ matrix.binary }}
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
          platform: macos14

      - name: Verify Deterministic Build
        uses: ./.github/actions/determinism-check
        with:
          sha1: ${{ steps.build.outputs.artifact_sha }}
          sha2: ${{ steps.rebuild.outputs.artifact_sha }}

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: mysql-client
          allowUpdates: true
          artifacts: ${{ steps.build.outputs.artifact_path }}
          token: ${{ secrets.GITHUB_TOKEN }}

  mysql-client-linux:
    strategy:
      matrix:
        binary: [mysql, mysqladmin]
        arch: [amd64]
        version: [8.0.36]
    name: Make a package with the mysql client binaries ${{ matrix.binary }} for ubuntu 20.04 and 22.04
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Package
        uses: ./.github/actions/mysql-linux
        id: build
        with:
          binary: ${{ matrix.binary }}
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Rebuild Package
        uses: ./.github/actions/mysql-linux
        id: rebuild
        with:
          binary: ${{ matrix.binary }}
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Verify Deterministic Build
        uses: ./.github/actions/determinism-check
        with:
          sha1: ${{ steps.build.outputs.artifact_sha }}
          sha2: ${{ steps.rebuild.outputs.artifact_sha }}

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: mysql-client
          allowUpdates: true
          artifacts: ${{ steps.build.outputs.artifact_path }}
          token: ${{ secrets.GITHUB_TOKEN }}

  mysql-client-linux-arm:
    strategy:
      matrix:
        binary: [mysql, mysqladmin]
        arch: [arm64]
        version: [8.0.40-31-1]
    name: Make a package with percona mysql client binaries ${{ matrix.binary }} for ubuntu 20.04 and 22.04
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Package
        uses: ./.github/actions/mysql-percona
        id: build
        with:
          binary: ${{ matrix.binary }}
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Rebuild Package
        uses: ./.github/actions/mysql-percona
        id: rebuild
        with:
          binary: ${{ matrix.binary }}
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Verify Deterministic Build
        uses: ./.github/actions/determinism-check
        with:
          sha1: ${{ steps.build.outputs.artifact_sha }}
          sha2: ${{ steps.rebuild.outputs.artifact_sha }}

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: mysql-client
          allowUpdates: true
          artifacts: ${{ steps.build.outputs.artifact_path }}
          token: ${{ secrets.GITHUB_TOKEN }}