name: MySQL client binaries lightweight packages
on:
  workflow_dispatch:
  push:
    branches:
      - mysql
jobs:
  mysql-client-macos11:
    strategy:
      matrix:
        binary: [mysql, mysqladmin]
        arch: [x86_64, arm64]
        version: [8.0.27, 8.0.28]
    name: Make a lightweight package for the ${{ matrix.arch }} ${{ matrix.binary }} blnary v${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Download source package
        run: curl -SsfL "https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-${{ matrix.version }}-macos11-${{ matrix.arch }}.tar.gz" -o mysql-client.tar.gz
      - name: Unpack source package
        run: tar xzf mysql-client.tar.gz
      - name: Remove unwanted binaries
        run: pushd mysql-${{ matrix.version }}-macos11-${{ matrix.arch }}/bin/ && (ls -1 | grep -v '^${{ matrix.binary }}$' | xargs rm) && popd
      - name: Repack package
        run: tar czf ${{ matrix.binary }}-${{ matrix.version }}-macos11-${{ matrix.arch }}.tar.gz mysql-${{ matrix.version }}-macos11-${{ matrix.arch }}
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: mysql-client
          allowUpdates: true
          artifacts: ${{ matrix.binary }}-${{ matrix.version }}-macos11-${{ matrix.arch }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
  mysql-client-macos14:
    strategy:
      matrix:
        binary: [mysql, mysqladmin]
        arch: [x86_64, arm64]
        version: [8.0.36]
    name: Make a lightweight package for the ${{ matrix.arch }} ${{ matrix.binary }} blnary v${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Download source package
        run: curl -SsfL "https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-${{ matrix.version }}-macos14-${{ matrix.arch }}.tar.gz" -o mysql-client.tar.gz
      - name: Unpack source package
        run: tar xzf mysql-client.tar.gz
      - name: Remove unwanted binaries
        run: pushd mysql-${{ matrix.version }}-macos14-${{ matrix.arch }}/bin/ && (ls -1 | grep -v '^${{ matrix.binary }}$' | xargs rm) && popd
      - name: Repack package
        run: tar czf ${{ matrix.binary }}-${{ matrix.version }}-macos14-${{ matrix.arch }}.tar.gz mysql-${{ matrix.version }}-macos14-${{ matrix.arch }}
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: mysql-client
          allowUpdates: true
          artifacts: ${{ matrix.binary }}-${{ matrix.version }}-macos14-${{ matrix.arch }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
  mysql-client-linux:
    strategy:
      matrix:
        binary: [mysql, mysqladmin]
        arch: [amd64]
        version: [8.0.36]
    name: Make a package with the mysql client binaries ${{ matrix.binary }} for ubuntu 20.04 and 22.04
    runs-on: ubuntu-latest
    steps:
      - name: Download source packagess
        run: |
          if [[ ${{ matrix.binary }} == "mysql" ]]; then
            LIB="client-core"
          elif [[ ${{ matrix.binary }} == "mysqladmin" ]]; then
            LIB="client"
          fi
          curl -SsfL "https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-community-${LIB}_${{ matrix.version }}-1ubuntu20.04_${{ matrix.arch }}.deb" -o client-ubuntu20.04.deb
          curl -SsfL "https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-community-${LIB}_${{ matrix.version }}-1ubuntu22.04_${{ matrix.arch }}.deb" -o client-ubuntu22.04.deb
      - name: Unpack source packages
        run: |
          mkdir 20.04
          dpkg-deb --extract client-ubuntu20.04.deb 20.04/
          mkdir 22.04
          dpkg-deb --extract client-ubuntu22.04.deb 22.04/
      - name: Copy desired binaries to clean bin folder
        run: |
          mkdir bin
          cp 20.04/usr/bin/${{ matrix.binary }} bin/${{ matrix.binary }}-20.04
          cp 22.04/usr/bin/${{ matrix.binary }} bin/${{ matrix.binary }}-22.04
      - name: Repack package
        run: tar czf ${{ matrix.binary }}-${{ matrix.version }}-ubuntu_multirelease-${{ matrix.arch }}.tar.gz bin
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: mysql-client
          allowUpdates: true
          artifacts: ${{ matrix.binary }}-${{ matrix.version }}-ubuntu_multirelease-${{ matrix.arch }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
