name: MySQL client binaries lightweight packages
on:
  workflow_dispatch:
  push:
    branches:
      - mysql
jobs:
  mysql-client-macos11:
    strategy:
      matrix:
        binary: [mysql, mysqladmin]
        arch: [x86_64, arm64]
        version: [8.0.27, 8.0.28]
    name: Make a lightweight package for the ${{ matrix.arch }} ${{ matrix.binary }} blnary v${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Download source package
        run: curl -SsfL "https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-${{ matrix.version }}-macos11-${{ matrix.arch }}.tar.gz" -o mysql-client.tar.gz
      - name: Unpack source package
        run: tar xzf mysql-client.tar.gz
      - name: Remove unwanted binaries
        run: pushd mysql-${{ matrix.version }}-macos11-${{ matrix.arch }}/bin/ && (ls -1 | grep -v '^${{ matrix.binary }}$' | xargs rm) && popd
      - name: Repack package
        run: tar czf ${{ matrix.binary }}-${{ matrix.version }}-macos11-${{ matrix.arch }}.tar.gz mysql-${{ matrix.version }}-macos11-${{ matrix.arch }}
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: mysql-client
          allowUpdates: true
          artifacts: ${{ matrix.binary }}-${{ matrix.version }}-macos11-${{ matrix.arch }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
  mysql-client-macos14:
    strategy:
      matrix:
        binary: [mysql, mysqladmin]
        arch: [x86_64, arm64]
        version: [8.0.36]
    name: Make a lightweight package for the ${{ matrix.arch }} ${{ matrix.binary }} blnary v${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Download source package
        run: curl -SsfL "https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-${{ matrix.version }}-macos14-${{ matrix.arch }}.tar.gz" -o mysql-client.tar.gz
      - name: Unpack source package
        run: tar xzf mysql-client.tar.gz
      - name: Remove unwanted binaries
        run: pushd mysql-${{ matrix.version }}-macos14-${{ matrix.arch }}/bin/ && (ls -1 | grep -v '^${{ matrix.binary }}$' | xargs rm) && popd
      - name: Repack package
        run: tar czf ${{ matrix.binary }}-${{ matrix.version }}-macos14-${{ matrix.arch }}.tar.gz mysql-${{ matrix.version }}-macos14-${{ matrix.arch }}
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: mysql-client
          allowUpdates: true
          artifacts: ${{ matrix.binary }}-${{ matrix.version }}-macos14-${{ matrix.arch }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
  mysql-client-linux:
    strategy:
      matrix:
        binary: [mysql, mysqladmin]
        arch: [x86_64,aarch64]
        version: [8.0.36]
    name: Make a package with the mysql client binaries ${{ matrix.binary }} for generic linux
    runs-on: ubuntu-latest
    steps:
      - name: Download source packagess
        run: |
          if [[ ${{ matrix.arch }} == "x86_64" ]]; then
            GLIBC="2.12"
          elif [[ ${{ matrix.binary }} == "aarch64" ]]; then
            GLIBC="2.12"
          fi
          curl -SsfL "https://cdn.mysql.com/archives/mysql-8.0/mysql-${{ matrix.version }}-linux-glibc${GLIBC}-${{ matrix.arch }}.tar.xz" -o linux-generic.tar.xz
      - name: Unpack source packages
        run: |
          mkdir linux-generic
          tar -xf linux-generic.tar.xz -C linux-generic --strip-components 1
      - name: Copy desired binaries to clean bin folder
        run: |
          mkdir bin
          cp linux-generic/bin/${{ matrix.binary }} bin/${{ matrix.binary }}
      - name: Repack package
        run: tar czf ${{ matrix.binary }}-${{ matrix.version }}-linux-generic-${{ matrix.arch }}.tar.gz bin
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: mysql-client
          allowUpdates: true
          artifacts: ${{ matrix.binary }}-${{ matrix.version }}-linux-generic-${{ matrix.arch }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
