name: Check package builds
on:
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # runner architecture defined here -> https://github.com/actions/runner-images
        os: [
          ubuntu-22.04,     # linux-amd64
          ubuntu-22.04-arm, # linux-arm64
          macos-13,         # darwin-amd64
          macos-13-xlarge   # darwin-arm64
        ]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # ratchet:actions/checkout@v3
      - uses: cashapp/activate-hermit@e49f5cb4dd64ff0b0b659d1d8df499595451155a # ratchet:cashapp/activate-hermit@v1
      - name: Update make (macos only)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install make
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
      - id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files: |
            pkgs/**
      - run: build-changed-pkgs
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
