name: Check package builds
on:
  pull_request:
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cashapp/activate-hermit@v1
      - id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files: |
            pkgs/**
      - run: build-changed-pkgs
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
