name: Build package
on:
  workflow_dispatch:
    inputs:
      package:
        description: "Package to build"
        required: true
        type: string
jobs:
  pkg:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # runner architecture defined here -> https://github.com/actions/runner-images
        os: [
          ubuntu-22.04,     # linux-amd64
          ubuntu-22.04-arm, # linux-arm64
          macos-13,         # darwin-amd64
          macos-13-xlarge   # darwin-arm64
        ]
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # ratchet:actions/checkout@v3
      - name: Init Hermit
        uses: cashapp/activate-hermit@e49f5cb4dd64ff0b0b659d1d8df499595451155a # ratchet:cashapp/activate-hermit@v1
      - name: Build
        id: build
        run: |
          make -C pkgs/${{ inputs.package }}
          make -s -C pkgs/${{ inputs.package }} version
          echo "VERSION=$(make -s -C pkgs/${{ inputs.package }} version)" >> $GITHUB_OUTPUT
      - name: Upload Release
        # Use old version of the release-action, as newer releases use node-20 which is not compatible with CentOS 7
        uses: ncipollo/release-action@8c78ca2662b7f5b8d5e5d5b5dbad3a5f38911fc0
        with:
          tag: ${{ inputs.package }}-${{ steps.build.outputs.VERSION }}
          allowUpdates: true
          replacesArtifacts: false
          artifacts: "pkgs/${{ inputs.package }}/${{ inputs.package }}-${{ steps.build.outputs.VERSION }}-*.tar.xz"
          token: ${{ secrets.GITHUB_TOKEN }}
