name: Build package
on:
  workflow_dispatch:
    inputs:
      package:
        description: "Package to build"
        required: true
        type: string
jobs:
  pkg:
    name: Build
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Init Hermit
        uses: cashapp/activate-hermit@v1
      - name: Build
        id: build
        run: |
          make -C pkgs/${{ inputs.package }}
          make -s -C pkgs/${{ inputs.package }} version
          echo "VERSION=$(make -s -C pkgs/${{ inputs.package }} version)" >> $GITHUB_OUTPUT
      - name: Upload Release
        # Use old version of the release-action, as newer releases use node-20 which is not compatible with CentOS 7
        uses: ncipollo/release-action@8c78ca2662b7f5b8d5e5d5b5dbad3a5f38911fc0
        with:
          tag: ${{ inputs.package }}-${{ steps.build.outputs.VERSION }}
          allowUpdates: true
          replacesArtifacts: false
          artifacts: "pkgs/${{ inputs.package }}/${{ inputs.package }}-${{ steps.build.outputs.VERSION }}-*.tar.xz"
          token: ${{ secrets.GITHUB_TOKEN }}
